// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageKind int32

const (
	Message_None                          Message_MessageKind = 0
	Message_Join                          Message_MessageKind = 1
	Message_Broadcast                     Message_MessageKind = 2
	Message_Custom                        Message_MessageKind = 3
	Message_OnAuthenticationFailedMessage Message_MessageKind = 11
	Message_OnJoinFailedMessage           Message_MessageKind = 12
	Message_OnJoinMessage                 Message_MessageKind = 13
	Message_OnOtherUserJoinMessage        Message_MessageKind = 14
	Message_OnOtherUserLeaveMessage       Message_MessageKind = 15
	Message_OnBroadcastMessage            Message_MessageKind = 16
)

var Message_MessageKind_name = map[int32]string{
	0:  "None",
	1:  "Join",
	2:  "Broadcast",
	3:  "Custom",
	11: "OnAuthenticationFailedMessage",
	12: "OnJoinFailedMessage",
	13: "OnJoinMessage",
	14: "OnOtherUserJoinMessage",
	15: "OnOtherUserLeaveMessage",
	16: "OnBroadcastMessage",
}

var Message_MessageKind_value = map[string]int32{
	"None":                          0,
	"Join":                          1,
	"Broadcast":                     2,
	"Custom":                        3,
	"OnAuthenticationFailedMessage": 11,
	"OnJoinFailedMessage":           12,
	"OnJoinMessage":                 13,
	"OnOtherUserJoinMessage":        14,
	"OnOtherUserLeaveMessage":       15,
	"OnBroadcastMessage":            16,
}

func (x Message_MessageKind) String() string {
	return proto.EnumName(Message_MessageKind_name, int32(x))
}

func (Message_MessageKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message struct {
	Kind                 Message_MessageKind `protobuf:"varint,1,opt,name=Kind,proto3,enum=Message_MessageKind" json:"Kind,omitempty"`
	Body                 *any.Any            `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetKind() Message_MessageKind {
	if m != nil {
		return m.Kind
	}
	return Message_None
}

func (m *Message) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type JoinMessageBody struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	RoomID               string   `protobuf:"bytes,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinMessageBody) Reset()         { *m = JoinMessageBody{} }
func (m *JoinMessageBody) String() string { return proto.CompactTextString(m) }
func (*JoinMessageBody) ProtoMessage()    {}
func (*JoinMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *JoinMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinMessageBody.Unmarshal(m, b)
}
func (m *JoinMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinMessageBody.Marshal(b, m, deterministic)
}
func (m *JoinMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinMessageBody.Merge(m, src)
}
func (m *JoinMessageBody) XXX_Size() int {
	return xxx_messageInfo_JoinMessageBody.Size(m)
}
func (m *JoinMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_JoinMessageBody proto.InternalMessageInfo

func (m *JoinMessageBody) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *JoinMessageBody) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *JoinMessageBody) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

type BroadcastMessageBody struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessageBody) Reset()         { *m = BroadcastMessageBody{} }
func (m *BroadcastMessageBody) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessageBody) ProtoMessage()    {}
func (*BroadcastMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *BroadcastMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessageBody.Unmarshal(m, b)
}
func (m *BroadcastMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessageBody.Marshal(b, m, deterministic)
}
func (m *BroadcastMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessageBody.Merge(m, src)
}
func (m *BroadcastMessageBody) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessageBody.Size(m)
}
func (m *BroadcastMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessageBody proto.InternalMessageInfo

func (m *BroadcastMessageBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type CustomMessageBody struct {
	Kind                 int32    `protobuf:"varint,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Body                 *any.Any `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomMessageBody) Reset()         { *m = CustomMessageBody{} }
func (m *CustomMessageBody) String() string { return proto.CompactTextString(m) }
func (*CustomMessageBody) ProtoMessage()    {}
func (*CustomMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *CustomMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomMessageBody.Unmarshal(m, b)
}
func (m *CustomMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomMessageBody.Marshal(b, m, deterministic)
}
func (m *CustomMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomMessageBody.Merge(m, src)
}
func (m *CustomMessageBody) XXX_Size() int {
	return xxx_messageInfo_CustomMessageBody.Size(m)
}
func (m *CustomMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_CustomMessageBody proto.InternalMessageInfo

func (m *CustomMessageBody) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *CustomMessageBody) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type ShortUser struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortUser) Reset()         { *m = ShortUser{} }
func (m *ShortUser) String() string { return proto.CompactTextString(m) }
func (*ShortUser) ProtoMessage()    {}
func (*ShortUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ShortUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortUser.Unmarshal(m, b)
}
func (m *ShortUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortUser.Marshal(b, m, deterministic)
}
func (m *ShortUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortUser.Merge(m, src)
}
func (m *ShortUser) XXX_Size() int {
	return xxx_messageInfo_ShortUser.Size(m)
}
func (m *ShortUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortUser.DiscardUnknown(m)
}

var xxx_messageInfo_ShortUser proto.InternalMessageInfo

func (m *ShortUser) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ShortUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OnJoinMessageBody struct {
	UserMap              map[string]*ShortUser `protobuf:"bytes,1,rep,name=UserMap,proto3" json:"UserMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OnJoinMessageBody) Reset()         { *m = OnJoinMessageBody{} }
func (m *OnJoinMessageBody) String() string { return proto.CompactTextString(m) }
func (*OnJoinMessageBody) ProtoMessage()    {}
func (*OnJoinMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *OnJoinMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnJoinMessageBody.Unmarshal(m, b)
}
func (m *OnJoinMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnJoinMessageBody.Marshal(b, m, deterministic)
}
func (m *OnJoinMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnJoinMessageBody.Merge(m, src)
}
func (m *OnJoinMessageBody) XXX_Size() int {
	return xxx_messageInfo_OnJoinMessageBody.Size(m)
}
func (m *OnJoinMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_OnJoinMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_OnJoinMessageBody proto.InternalMessageInfo

func (m *OnJoinMessageBody) GetUserMap() map[string]*ShortUser {
	if m != nil {
		return m.UserMap
	}
	return nil
}

type OnOtherUserJoinMessageBody struct {
	User                 *ShortUser `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OnOtherUserJoinMessageBody) Reset()         { *m = OnOtherUserJoinMessageBody{} }
func (m *OnOtherUserJoinMessageBody) String() string { return proto.CompactTextString(m) }
func (*OnOtherUserJoinMessageBody) ProtoMessage()    {}
func (*OnOtherUserJoinMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *OnOtherUserJoinMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnOtherUserJoinMessageBody.Unmarshal(m, b)
}
func (m *OnOtherUserJoinMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnOtherUserJoinMessageBody.Marshal(b, m, deterministic)
}
func (m *OnOtherUserJoinMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnOtherUserJoinMessageBody.Merge(m, src)
}
func (m *OnOtherUserJoinMessageBody) XXX_Size() int {
	return xxx_messageInfo_OnOtherUserJoinMessageBody.Size(m)
}
func (m *OnOtherUserJoinMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_OnOtherUserJoinMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_OnOtherUserJoinMessageBody proto.InternalMessageInfo

func (m *OnOtherUserJoinMessageBody) GetUser() *ShortUser {
	if m != nil {
		return m.User
	}
	return nil
}

type OnOtherUserLeaveMessageBody struct {
	User                 *ShortUser `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OnOtherUserLeaveMessageBody) Reset()         { *m = OnOtherUserLeaveMessageBody{} }
func (m *OnOtherUserLeaveMessageBody) String() string { return proto.CompactTextString(m) }
func (*OnOtherUserLeaveMessageBody) ProtoMessage()    {}
func (*OnOtherUserLeaveMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *OnOtherUserLeaveMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnOtherUserLeaveMessageBody.Unmarshal(m, b)
}
func (m *OnOtherUserLeaveMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnOtherUserLeaveMessageBody.Marshal(b, m, deterministic)
}
func (m *OnOtherUserLeaveMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnOtherUserLeaveMessageBody.Merge(m, src)
}
func (m *OnOtherUserLeaveMessageBody) XXX_Size() int {
	return xxx_messageInfo_OnOtherUserLeaveMessageBody.Size(m)
}
func (m *OnOtherUserLeaveMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_OnOtherUserLeaveMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_OnOtherUserLeaveMessageBody proto.InternalMessageInfo

func (m *OnOtherUserLeaveMessageBody) GetUser() *ShortUser {
	if m != nil {
		return m.User
	}
	return nil
}

type OnBroadcastMessageBody struct {
	From                 *ShortUser `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	Body                 []byte     `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OnBroadcastMessageBody) Reset()         { *m = OnBroadcastMessageBody{} }
func (m *OnBroadcastMessageBody) String() string { return proto.CompactTextString(m) }
func (*OnBroadcastMessageBody) ProtoMessage()    {}
func (*OnBroadcastMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *OnBroadcastMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnBroadcastMessageBody.Unmarshal(m, b)
}
func (m *OnBroadcastMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnBroadcastMessageBody.Marshal(b, m, deterministic)
}
func (m *OnBroadcastMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnBroadcastMessageBody.Merge(m, src)
}
func (m *OnBroadcastMessageBody) XXX_Size() int {
	return xxx_messageInfo_OnBroadcastMessageBody.Size(m)
}
func (m *OnBroadcastMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_OnBroadcastMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_OnBroadcastMessageBody proto.InternalMessageInfo

func (m *OnBroadcastMessageBody) GetFrom() *ShortUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OnBroadcastMessageBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("Message_MessageKind", Message_MessageKind_name, Message_MessageKind_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*JoinMessageBody)(nil), "JoinMessageBody")
	proto.RegisterType((*BroadcastMessageBody)(nil), "BroadcastMessageBody")
	proto.RegisterType((*CustomMessageBody)(nil), "CustomMessageBody")
	proto.RegisterType((*ShortUser)(nil), "ShortUser")
	proto.RegisterType((*OnJoinMessageBody)(nil), "OnJoinMessageBody")
	proto.RegisterMapType((map[string]*ShortUser)(nil), "OnJoinMessageBody.UserMapEntry")
	proto.RegisterType((*OnOtherUserJoinMessageBody)(nil), "OnOtherUserJoinMessageBody")
	proto.RegisterType((*OnOtherUserLeaveMessageBody)(nil), "OnOtherUserLeaveMessageBody")
	proto.RegisterType((*OnBroadcastMessageBody)(nil), "OnBroadcastMessageBody")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x9d, 0xd3, 0xb4, 0x5b, 0x6f, 0xdb, 0x2d, 0x35, 0x55, 0x57, 0x3a, 0x31, 0x4a, 0x9e, 0xa2,
	0x3d, 0x64, 0xa8, 0x08, 0x09, 0x10, 0x3c, 0xac, 0x1b, 0x15, 0x85, 0x6d, 0x11, 0x99, 0x78, 0x80,
	0x37, 0xb7, 0x31, 0x6d, 0x44, 0x63, 0x57, 0x89, 0x3b, 0x91, 0x1f, 0xe1, 0x6b, 0xf8, 0x14, 0x3e,
	0x06, 0xd9, 0x71, 0x42, 0x3a, 0x8a, 0xc4, 0x9e, 0x7a, 0xef, 0x39, 0xc7, 0x27, 0xd7, 0xf7, 0xb8,
	0xd0, 0x8a, 0x68, 0x92, 0x90, 0x39, 0x75, 0x57, 0x31, 0x17, 0xbc, 0xff, 0x70, 0xce, 0xf9, 0x7c,
	0x49, 0x4f, 0x55, 0x37, 0x5d, 0x7f, 0x3d, 0x25, 0x2c, 0xcd, 0x28, 0xfb, 0xa7, 0x01, 0xbb, 0x57,
	0x99, 0x18, 0x3b, 0x60, 0x7e, 0x08, 0x59, 0xd0, 0x43, 0x03, 0xe4, 0xec, 0x0f, 0x3b, 0xae, 0xc6,
	0xf3, 0x5f, 0xc9, 0xf9, 0x4a, 0x21, 0x95, 0x23, 0x1e, 0xa4, 0x3d, 0x63, 0x80, 0x9c, 0xc6, 0xb0,
	0xe3, 0x66, 0xfe, 0x6e, 0xee, 0xef, 0x9e, 0xb1, 0xd4, 0x57, 0x0a, 0xfb, 0x17, 0x82, 0x46, 0xe9,
	0x3c, 0xde, 0x03, 0xf3, 0x9a, 0x33, 0x6a, 0xed, 0xc8, 0xea, 0x3d, 0x0f, 0x99, 0x85, 0x70, 0x0b,
	0xea, 0xa3, 0x98, 0x93, 0x60, 0x46, 0x12, 0x61, 0x19, 0x18, 0xa0, 0x76, 0xbe, 0x4e, 0x04, 0x8f,
	0xac, 0x0a, 0x7e, 0x02, 0x8f, 0x3c, 0x76, 0xb6, 0x16, 0x0b, 0xca, 0x44, 0x38, 0x23, 0x22, 0xe4,
	0x6c, 0x4c, 0xc2, 0x25, 0x0d, 0xb4, 0xa7, 0xd5, 0xc0, 0x87, 0xf0, 0xc0, 0x63, 0xd2, 0x69, 0x93,
	0x68, 0xe2, 0x36, 0xb4, 0x32, 0x22, 0x87, 0x5a, 0xb8, 0x0f, 0x5d, 0x8f, 0x79, 0x62, 0x41, 0xe3,
	0x4f, 0x09, 0x8d, 0xcb, 0xdc, 0x3e, 0x3e, 0x82, 0xc3, 0x12, 0x77, 0x49, 0xc9, 0x2d, 0xcd, 0xc9,
	0x03, 0xdc, 0x05, 0xec, 0xb1, 0x62, 0xc8, 0x1c, 0xb7, 0xec, 0xcf, 0x70, 0x50, 0x72, 0x91, 0x37,
	0xc6, 0x5d, 0xa8, 0x49, 0x83, 0xc9, 0x85, 0xda, 0x63, 0xdd, 0xd7, 0x9d, 0xc4, 0x6f, 0xe8, 0x2c,
	0xa6, 0x42, 0x6d, 0xad, 0xee, 0xeb, 0x4e, 0xe2, 0x3e, 0xe7, 0xd1, 0xe4, 0xa2, 0x57, 0xc9, 0xf0,
	0xac, 0xb3, 0x4f, 0xa0, 0x73, 0xf7, 0x83, 0xca, 0x1f, 0xeb, 0xdd, 0x4b, 0xf7, 0xa6, 0xde, 0xf2,
	0x47, 0x68, 0x67, 0x2b, 0xbb, 0x23, 0x2c, 0xe2, 0xac, 0xde, 0x3b, 0xb8, 0xe7, 0x50, 0xbf, 0x59,
	0xf0, 0x58, 0xc8, 0xe9, 0x71, 0x07, 0xaa, 0x13, 0x16, 0xd0, 0xef, 0xda, 0x2b, 0x6b, 0xe4, 0x07,
	0xae, 0x49, 0x44, 0xf5, 0x7d, 0x54, 0x6d, 0xff, 0x40, 0xd0, 0xde, 0xd8, 0xba, 0x1a, 0xe5, 0x25,
	0xec, 0x4a, 0x9f, 0x2b, 0xb2, 0xea, 0xa1, 0x41, 0xc5, 0x69, 0x0c, 0x1f, 0xbb, 0x7f, 0x89, 0x5c,
	0xad, 0x78, 0xcb, 0x44, 0x9c, 0xfa, 0xb9, 0xbe, 0x3f, 0x86, 0x66, 0x99, 0xc0, 0x16, 0x54, 0xbe,
	0xd1, 0x54, 0xef, 0x56, 0x96, 0x78, 0x00, 0xd5, 0x5b, 0xb2, 0x5c, 0x53, 0x7d, 0x29, 0x70, 0x8b,
	0xb9, 0xfd, 0x8c, 0x78, 0x65, 0xbc, 0x40, 0xf6, 0x6b, 0xe8, 0x6f, 0x8f, 0x5e, 0x0d, 0x78, 0x0c,
	0xa6, 0x84, 0x95, 0xed, 0xa6, 0x85, 0xc2, 0xed, 0x37, 0x70, 0xf4, 0x8f, 0xc7, 0xf1, 0x5f, 0xc7,
	0x2f, 0xe5, 0xbb, 0xdb, 0x9a, 0xe6, 0x31, 0x98, 0xe3, 0x98, 0x47, 0xdb, 0x4e, 0x4a, 0xbc, 0x48,
	0xdb, 0xf8, 0x93, 0xf6, 0xf0, 0x04, 0x6a, 0xef, 0xc2, 0x29, 0x89, 0x43, 0x3c, 0x00, 0xf3, 0x9c,
	0x33, 0x86, 0xf7, 0xf2, 0xff, 0x68, 0xbf, 0xa8, 0xec, 0x1d, 0x07, 0x3d, 0x45, 0x23, 0xf3, 0x8b,
	0xb1, 0x9a, 0x4e, 0x6b, 0x2a, 0xe0, 0x67, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x96, 0x25, 0x9f,
	0xba, 0x18, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HibariClient is the client API for Hibari service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HibariClient interface {
	Conn(ctx context.Context, opts ...grpc.CallOption) (Hibari_ConnClient, error)
}

type hibariClient struct {
	cc *grpc.ClientConn
}

func NewHibariClient(cc *grpc.ClientConn) HibariClient {
	return &hibariClient{cc}
}

func (c *hibariClient) Conn(ctx context.Context, opts ...grpc.CallOption) (Hibari_ConnClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Hibari_serviceDesc.Streams[0], "/Hibari/Conn", opts...)
	if err != nil {
		return nil, err
	}
	x := &hibariConnClient{stream}
	return x, nil
}

type Hibari_ConnClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type hibariConnClient struct {
	grpc.ClientStream
}

func (x *hibariConnClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hibariConnClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HibariServer is the server API for Hibari service.
type HibariServer interface {
	Conn(Hibari_ConnServer) error
}

// UnimplementedHibariServer can be embedded to have forward compatible implementations.
type UnimplementedHibariServer struct {
}

func (*UnimplementedHibariServer) Conn(srv Hibari_ConnServer) error {
	return status.Errorf(codes.Unimplemented, "method Conn not implemented")
}

func RegisterHibariServer(s *grpc.Server, srv HibariServer) {
	s.RegisterService(&_Hibari_serviceDesc, srv)
}

func _Hibari_Conn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HibariServer).Conn(&hibariConnServer{stream})
}

type Hibari_ConnServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type hibariConnServer struct {
	grpc.ServerStream
}

func (x *hibariConnServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hibariConnServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Hibari_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hibari",
	HandlerType: (*HibariServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Conn",
			Handler:       _Hibari_Conn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
